apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  hostPID: true
  volumes:
    - name: ramdisk
      hostPath:
        path: /mnt/disks/ram
  terminationGracePeriodSeconds: 60
  containers:
    - image: busybox
      name: busybox
      command: ["sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: ramdisk
          mountPath: /data
          readOnly: true

